spring.application.name=backendDS

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pruebaDatasoft}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin12345}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false

app.jwt.secret=DatasoftBackendSecretKeyForJwtSigningMustBeAtLeastThirtyTwoBytes
app.jwt.expiration-ms=86400000
